baseURL = "http://example.org/"
languageCode = "en-us"
title = "- Billionaires United -   "
theme = "hugo-assembly"

# Metadata
[params]
  author = "Walter Reid"
  description = "Person of compassion"

# banner section (from here on is for Billionaires theme)
[params.banner]
  title = "This is Billionaires United "
  byline = "Democracies Loudest Voice"

[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Home"
  services = "Services"
  welcome = "Welcome"
  contact = "Contact Us"

# Services section
[params.services]
  enable = true
  title = "Services to the Community"
  subtitle = "Divide and Conquer - Greed is Good - Fear works - Stoke the Hate"

  [[params.services.item]]
    weight = "A"
    description = "We support the Supreme Court decision Citizens United vs FEC and want to expand the rights of corporations to be heard in government, on the air waves.  Messages of dispair, fear, hate are the messages we use to confuse issues and to motivate the elderly with mixed messages of safety and freedom."
    button_item_info = "Aristocracy"

  [[params.services.item]]
    weight = "B"
    description = "Primarily, our stategy is to promote ignorance, hate, dispair in the Democratic system.  Our Think Tanks have strategized and learned the best way to achieve a aristacracy is to dis-enfranchize the votor de-fund the government regulations "
    button_item_info = "Voter Suppression"

  [[params.services.item]]
    weight = "C"
    description = "Education is for the Privileged and is wasted on the common man.  The primary goal is access to opportunity.  By dividing the community into segments we feel it will be easier to deprive the populous of education.  Education promotes contempt and a aristocracy can not thrive in a contemptious populous."
    button_item_info = "Close Public Schools"

# Welcome section
[params.welcome]
  enable = true
  title = "Welcome Billionaire"
  subtitle = "You have Made it to the top 1% and you want to pull up the Ladder of Opportunity so others can not follow." 
  description = "This is <strong>Billionaires United</strong>, an organization to inform Democratic societies how to become an aristocracy."
  button_text = "Call Now"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
#   button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "&copy; Billionaires United | All rights reserved."
  twitter = ""
  facebook = ""
  instagram = ""
