baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hugo-assembly"

# Metadata
[params]
  author = "Walter Reid"
  description = "Person of compassion"

# banner section (from here on is for Billionaires theme)
[params.banner]
  title = "This is Billionaires United "
  byline = "Democracies Loudest Voice"

[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Home"
  services = "Services"
  welcome = "Welcome"
  donate = "Donate"
  contact = "Contact Us"

# Services section
[params.services]
  enable = true
  title = "Community Service"
  subtitle = "Safety, Community, Obedience "

  [[params.services.item]]
    weight = "A"
    description = "We support the Supreme Court Decision Citizens United vs FEC and want to expand the right of anonymous corporate speech.  Messages of despair, fear, hate are messages that work well to attract the ignorant the elderly and the racist voters using messages of exclusion, safety and freedom. <p>                                                                                                </p>"
    button_item_info = "Anonymous Speech"

  [[params.services.item]]
    weight = "B"
    description = "Primarily, our strategy is to promote ignorance, hate and despair.  We love NEWS if properly sanctioned.  Our Think Tanks have advised, the best way to achieve an autocracy is to dis-enfranchise the voter and de-fund the government.  Work is a privilege.  Vote is a privilege.  If you work and you contribute to the state you can vote.  Vote wrong and you lose the privilege to work."
    button_item_info = "Earned Vote"

  [[params.services.item]]
    weight = "C"
    description = "We believe in STATE Education.  Re-education of the populous is important.  If persons work and vote appropriately they will receive free education.  If persons vote in-appropriately they will receive special re-education programs.   Proper education promotes unity and prosperity.   Improper education promotes contempt and an aristocracy cannot thrive with a contemptuous populous."
    button_item_info = "Priority Educations"


# Welcome section
[params.welcome]
  enable = true
  title = "Welcome Billionaire"
  subtitle = "You have Made it to the top 1% and you want to pull up the Ladder of Opportunity so others can not follow." 
  description = "This is <strong>Billionaires United</strong>, an organization to inform Democratic societies how to become an aristocracy."
  button_text = "Call Now"

# Donate section
[params.donate]
  enable = true
  title = " Help the Elite "
  subtitle = "Fund Billionaires for greeeds sake"
  button_text = "Donate"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
#   button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "&copy; Billionaires United | All rights reserved."
  twitter = ""
  facebook = ""
  instagram = ""
