baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hugo-assembly"

# Metadata
[params]
  author = "Walter Reid"
  description = "Person of compassion"

# banner section (from here on is for Billionaires theme)
[params.banner]
  title = "This is Billionaires United "
  byline = "Democracies Loudest Voice"

[params.actions] # CTAs
  enable = true
  register = "CTA Now!"

# Navigation section
[params.nav]
  home = "Home"
  services = "Services"
  welcome = "Welcome"
  donate = "Donate"
  contact = "Contact Us"

# Services section
[params.services]
  enable = true
  title = "Community Service"
  subtitle = "Division, Greed, Fear, Hate "

  [[params.services.item]]
    weight = "A"
    description = "We support the Supreme Court decision Citizens United vs FEC and want to expand the right of anonymous corporate speech.  Messages of despair, fear, hate are messages that work well to attract the ignoratant the elderly and the racist voters using messages of exclusion, safety and freedom. <p>                                                                                                </p>"
    button_item_info = "AnonymousSpeech"

  [[params.services.item]]
    weight = "B"
    description = "Primarily, our strategy is to promote ignorance, hate and despair in the Democratic system.  Our Think Tanks have strategized and learned the best way to achieve an aristocracy is to dis-enfranchise the voter and de-fund the government. Voters, no age limit just income of $50k+ and you earn the right to vote.  Billionaires need freedom from regulation to fund other voters if necessary. "
    button_item_info = "EarnedVote"

  [[params.services.item]]
    weight = "C"
    description = "Education is a Privilege we cant afford. Education is wasted on the poor.  The primary realization is education is opportunity. The goal is to deprive the populous of education to help suppress opportunity and ensure a healthy aristocracy.  Education promotes contempt and an aristocracy cannot thrive with a contemptuous populous."
    button_item_info = "Educations A Privilege"


# Welcome section
[params.welcome]
  enable = true
  title = "Welcome Billionaire"
  subtitle = "You have Made it to the top 1% and you want to pull up the Ladder of Opportunity so others can not follow." 
  description = "This is <strong>Billionaires United</strong>, an organization to inform Democratic societies how to become an aristocracy."
  button_text = "Call Now"

# Donate section
[params.donate]
  enable = true
  title = " Help the Elite "
  subtitle = "Fund Billionaires for greeeds sake"
  button_text = "Donate"

# Contact section
[params.contact]
  enable = true
#   title = "Get In Touch"
#   message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
#   name_placeholder = "Your name"
#   email_placeholder = "Your email"
#   email_disclaimer = "We'll never share your email with anyone else."
#   message_placeholder = "Please enter a message."
#   button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "&copy; Billionaires United | All rights reserved."
  twitter = ""
  facebook = ""
  instagram = ""
